import type { Metadata } from "next";

import "./globals.css";
// If you see a TypeScript error about missing type declarations for CSS modules,
// you can add a declaration file (e.g., globals.d.ts) with:
// declare module '*.css';
import { AppProvider } from "@/context/AppContext";
import { SocketProvider } from "@/context/SocketContext";




export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body       
      >
        <AppProvider>
          <SocketProvider>
             {children}
          </SocketProvider>
        </AppProvider>  
      </body>
    </html>
  );
}
